### ISSUE TITLE
Request to add an additional DNS provider - https://securedns.eu/

### ISSUE THREAD

**Issue by 7dowWilkes** [qdm12/cloudflare-dns-server#11]
It would be absolutely cool if SecureDNS could be included as an additional selectable DNS provider. SecureDNS could also be used directly as an adblocker, by using a corresponding tls-hostname - see here: https://securedns.eu/

Sorry if I post wrong here, but I'm new here and have not found another way ... and I´am just a enduser.

Thank you!

**Comment by qdm12** [comment]
Hi there,

It's added, simply set `-e PROVIDER=securedns`  😉 

On a side note, I am working on a related project [*updated*](https://github.com/qdm12/updated) which updates periodically a list of IP addresses and hostnames from various lists and builds separate block lists (Ads, Malicious, NSA, etc.). This Docker image bundles lists built from this updated repository, so you might be able to complement securedns with additional block lists and Unbound.

But this updated currently runs with shell scripting which is terrible for advanced stuff, but I should release a Go program replacing it soon. For example, the new version now collects malicious hostnames (about 27000) and look them all up (in parallel 😎) to get their IP addresses and block these too.

So it's gonna rock security wise 💯  I will post back once it's done 👍

**Comment by 7dowWilkes** [comment]
Thank you for your support and your ideas! Great job, keep it up 👍🏻👏🏻
