### ISSUE TITLE
Disable DNS Caching

### ISSUE THREAD

**Issue by AndrewPaglusch** [qdm12/cloudflare-dns-server#13]
I've configured PiHole to send queries to this image. PiHole already handles DNS caching, so it would be nice if there was an option to disable caching inside of this image so that PiHole can handle all of that for us. That way, we're not double-caching results.

I did some light research to find the necessary Unbound config that would be needed to accomplish this, but the best solution I came across was to simply set the TTL to something very low with the `cache-min-ttl` option, which should produce the desired outcome.

**Comment by qdm12** [comment]
Good idea, I'll add the option through an environment variable. I'm however quite busy until the weekend so it will take me a few days to add the feature. Thanks!

**Comment by AndrewPaglusch** [comment]
Great! Happy to hear you like the idea

**Comment by qdm12** [comment]
Do you think setting `msg-cache-size: 0` could solve it? ([Link](https://nlnetlabs.nl/documentation/unbound/unbound.conf/)) Or maybe ` key-cache-size: 0`?

It also looks that setting `forward-no-cache: yes` would solve it in our case.

**Comment by AndrewPaglusch** [comment]
Good find. I think the `forward-no-cache` option is what we're looking for.
