### ISSUE TITLE
since the update (caching yes / no) docker-container crashes

### ISSUE THREAD

**Issue by 7dowWilkes** [qdm12/cloudflare-dns-server#16]
since the update (caching yes / no) my Docker container crashes constantly. I am using the Docker host network. This functioned smoothly in the past. Please help. The log is attached.

[log.pdf](https://github.com/qdm12/cloudflare-dns-server/files/3738160/log.pdf)

**Comment by qdm12** [comment]
I am testing it on my machine and it seems to work, would you mind sharing your docker-compose or docker run command?

Also why do you run it in the host network?

**Comment by 7dowWilkes** [comment]
I use the gui of the Docker-Application from Synology-NAS (no separately docker-compose nor docker-command) to create the container. I use the host network, because it was the only way to adress this container from my Pi-hole which runs in a independent container with mavlan-network. I don´t know what's now different to my past setup when the container was running correctly. The network bridge-mode also does not solve the problem. I also tried several DNS-providers.

Sorry for the inconvenience...

**Comment by qdm12** [comment]
No problem, did you try disabling some features as mentioned above? Set some environment variables to `off` such as `CACHING` or `BLOCK_MALICIOUS` to see if it works. Also, does it crash at start or after?

**Comment by qdm12** [comment]
It seems the Unbound process is launched successfully and then killed by an outside thing, likely your host OS. I tested it on my Synology NAS as well and it works.

Did you check your memory usage?

**Comment by 7dowWilkes** [comment]
Hi Quentin, thank you for your tests and clarifications. I tried several things (try and error) but I can not find the problem. The memory usage is ok, also the cpu-utilization. I will search further. The problem definitely seems to be on my side.

**Comment by 7dowWilkes** [comment]
Running "as root" did not solve my problem. I can not find the error in my system. I think you can close this thread. I'll let you know if I know more ... thank you again

**Comment by qdm12** [comment]
Oh wait, I might know, what's your CPU architecture? Or at least what's your Synology model?

As Unbound is now built from source in the docker build and not simply downloaded and installed, that might be a problem.

**Comment by qdm12** [comment]
What you can also try with a terminal is:

```sh
wget https://github.com/qdm12/cloudflare-dns-server/archive/02be30420dd36a001a4889d0ab39101060a7af4c.zip -O dns.zip
unzip dns.zip
rm dns.zip
cd dns
docker build -t qmcgaw/cloudflare-dns-server .
```

to build an older version of the docker image. I'll add more documentation on how to do it, so that you can try with other commits to see when it started failing.

**Comment by 7dowWilkes** [comment]
I have a Synology DS 716+ with Intel Celeron N3150, Quad Core | Threads=4 | FPU=Yes | Package Arch=Braswell | RAM=DDR3 8 GB (own RAM-Upgrade).
I will try your suggestion ...
Thx

**Comment by qdm12** [comment]
Hi, I've added documentation [here](https://github.com/qdm12/cloudflare-dns-server#build-the-image-yourself), please try it out 👍

**Comment by qdm12** [comment]
It seems like the container crashes on my side with a `Segmentation fault`, I am not sure if that's a hardware problem or not really, as I have tried with various Unbound versions. For now, use the `--restart=always` flag or `restart: always` docker-compose config to remedy this.

I will close the issue for now. I am also reworking hard the whole image to run supervised by a Go written program and not shell, so that might solve your problem.

There is also a new [Slack channel](https://join.slack.com/t/qdm12/shared_invite/enQtODMwMDQyMTAxMjY1LTU1YjE1MTVhNTBmNTViNzJiZmQwZWRmMDhhZjEyNjVhZGM4YmIxOTMxOTYzN2U0N2U2YjQ2MDk3YmYxN2NiNTc) if you want to join to keep updated and participate in the discussion 👍
