### ISSUE TITLE
error: can't bind socket: permission denied.

### ISSUE THREAD

**Issue by thayneq** [qdm12/cloudflare-dns-server#2]
Hi, I am testing your build from scratch on a synology, and here is what I'm seeing. I'm a bit confused because from your most recent changes, it sounds like running as a non-root-user shouldn't be a problem, but clearly it is. Can you help?

```bash
docker run -it --rm --name dns -p 53:53/udp -e VERBOSITY=5 -e VERBOSITY_DETAILS=4 -e BLOCK_MALICIOUS=off qmcgaw/cloudflare-dns-server
Unable to find image 'qmcgaw/cloudflare-dns-server:latest' locally
latest: Pulling from qmcgaw/cloudflare-dns-server
4fe2ade4980c: Already exists 
0cd970152cc6: Pull complete 
0cd8ed03c739: Pull complete 
857cf1d27e1d: Pull complete 
ba942c51bb57: Pull complete 
013c5f68402b: Pull complete 
0b624eaa3c30: Pull complete 
283041182f9d: Pull complete 
970357afc184: Pull complete 
Digest: sha256:88923bee0befbb9fadd00a67923dd3f9999196d600c0fa6acc8147b28c3ffddd
Status: Downloaded newer image for qmcgaw/cloudflare-dns-server:latest
 =========================================
 =========================================
 === CLOUDFLARE DNS OVER TLS CONTAINER ===
 =========================================
 =========================================
 == by github.com/qdm12 - Quentin McGaw ==

Running as nonrootuser
Unbound version: 1.7.3
Unbound listening UDP port: 53
Verbosity level set to 5 on 5
Verbosity details level set to 4 on 4
Malicious hostnames and ips blocking is off
[1542342706] unbound[27:0] notice: Start of unbound 1.7.3.
[1542342706] unbound[27:0] debug: creating udp4 socket 0.0.0.0 53
[1542342706] unbound[27:0] error: can't bind socket: Permission denied for 0.0.0.0 port 53 (len 16)
[1542342706] unbound[27:0] fatal error: could not open ports

 =========================================
 Unbound exit with status 1
 =========================================
```

**Comment by thayneq** [comment]
I dug into this a bit deeper, and I really can't figure out what's wrong. Is there an easy way to test this with a root user? It appears you have hard-coded "nonrootuser" deep into this application, so I'm guessing not.

**Comment by qdm12** [comment]
Thanks for letting me know this issue.

I tested the same latest version (SHA256 `88923bee0befbb9fadd00a67923dd3f9999196d600c0fa6acc8147b28c3ffddd` on two different machines (one is a synology) with the same environment variables as yours and it works which is odd... 

What I would advise you to do is to run:

```bash
docker run -d -e LISTENINGPORT=8053 -p 53:8053/udp qmcgaw/cloudflare-dns-server
```

This will run without root and should not have any low port binding problem. 

A little bonus, add `--user=root` (or any other such as `$UID`) to your Docker command to run with that user. Although root is unadvised, it's not too bad in this case as the Unbound process runs as nonrootuser even when launched as root.

Let me know how it goes

**Comment by thayneq** [comment]
yeah that totally worked. So I'm confused though.... I figured the permission error would be because you're trying to grab port 53 on the HOST, but it seems this erros was due to trying to use port 53 on the container. That's odd right? How are you able to map port 53 on the container without root, or --network=host?

**Comment by qdm12** [comment]
not even, I am using a simple bridge network with `-p 53:53/udp`. That's quite odd indeed. I'm playing with Unbound permissions to bind on low ports in the Dockerfile with the **libcap** library so maybe that depends on the host at run. I don't see any other explanation unfortunately!

**Comment by thayneq** [comment]
I did the above and it returned "0", so I assume this means I do have support in the kernel.

**Comment by qdm12** [comment]
Ok then I have no idea. I have a Synology DS918+ with the same DSM and it works. Very odd. I have updated the Reddit post. I might raise an issue on Moby/Docker because it could potentially be somehow alarming in terms of security/portability

**Comment by thayneq** [comment]
Ok. Thanks for all your help!! Let me know if you need any more info from me if you raise that issue. In the mean time, I don’t see any problem with just using 53:8053/udp. It appears to be working perfectly, aside from the other issue I raised in a separate thread.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thayneq** [comment]
Still doesn't bind. Here is the output:
```
# docker pull qmcgaw/cloudflare-dns-server
Using default tag: latest
latest: Pulling from qmcgaw/cloudflare-dns-server
4fe2ade4980c: Already exists 
3f7c2f5bc365: Pull complete 
5ef8c6e11719: Pull complete 
365cf6b9b2bf: Pull complete 
71110e53a8b0: Pull complete 
18b6ef986220: Pull complete 
bac20ce62a26: Pull complete 
6439c1c68d06: Pull complete 
754821d7a7ac: Pull complete 
Digest: sha256:09e88ca8b7e874b1df7414b11750b101bf275c4dad40967f17aa89291d35bde7
Status: Downloaded newer image for qmcgaw/cloudflare-dns-server:latest

# docker run -it --rm -p 10000:53/udp qmcgaw/cloudflare-dns-server
 =========================================
 =========================================
 === CLOUDFLARE DNS OVER TLS CONTAINER ===
 =========================================
 =========================================
 == by github.com/qdm12 - Quentin McGaw ==

Running as nonrootuser
Unbound version: 1.7.3
Unbound listening UDP port: 53
Verbosity level set to 1 on 5
Verbosity details level set to 0 on 4
Malicious hostnames and ips blocking is on
156944 malicious hostnames and 16079 malicious IP addresses blacklisted
[1542468525] unbound[35:0] error: can't bind socket: Permission denied for 0.0.0.0
[1542468525] unbound[35:0] fatal error: could not open ports

 =========================================
 Unbound exit with status 1
 =========================================
```

**Comment by jollyjester** [comment]
Just to say that i'm seeing the same problem now. I updated my DSM to latest then updated the docker container to the latest build and its got the same error as above.   It has been working beautifully upto this point.  Sorry i cant tell if it was the DSM upgrade or the newer docker that is causing the problem
[1547118860] unbound[34:0] error: can't bind socket: Permission denied for 0.0.0.0
[1547118860] unbound[34:0] fatal error: could not open ports

**Comment by jollyjester** [comment]
DSM upgrade was from : DSM 6.2.1-23824 Update 2 to DSM 6.2.1-23824 Update 4

**Comment by jollyjester** [comment]
I'd last rebuilt the docker container about 3 weeks ago...

**Comment by jollyjester** [comment]
changing the port on the container to 8053 as above fixed

**Comment by qdm12** [comment]
I just pulled the latest version and it works on both my Windows machine, my Synology NAS and my Alpine server; but my pull gives me a `Digest: sha256:658cbd435f6302c6ffe532cac66b3308e08722242e332e38e9108475b4a8e125` which is different than yours, so you might be pulling an older version for some reason.

If `docker pull` doesn't work, try `docker build -t qmcgaw/cloudflare-dns-server https://github.com/qdm12/cloudflare-dns-server.git` to build the image yourself and it should work. Let me know if it still doesn't work. Thanks !

**Comment by jollyjester** [comment]
Mine was:-
Digest: sha256:658cbd435f6302c6ffe532cac66b3308e08722242e332e38e9108475b4a8e125 which matches yours and still had the same problem.  Oh well the port work around is not end of the world and it now works again

**Comment by qdm12** [comment]
Oh sorry about that, I've mistaken the old comment from thayneq.

I understand mapping to another port works perfectly for you, but would you mind trying to build it with `docker build --no-cache -t qmcgaw/cloudflare-dns-server https://github.com/qdm12/cloudflare-dns-server.git` and see if it works on port 53?

Also another alternative is to run it with the flag `--user=root` or add `user: "root"` in your docker-compose.yml file. This way unbound will be able to bind to port 53 UDP and will drop privileges as soon as it does the binding. I might switch back to root user for launching to container, in order to avoid any end user issue similar to yours.

Also my DSM in one version behind the latest version so that could be a reason perhaps, although it's unlikely.
