### ISSUE TITLE
Is there anyway to verify that the DoT is working?

### ISSUE THREAD

**Issue by TachyonRSA** [qdm12/cloudflare-dns-server#21]
Since we cannot use 1.1.1.1/help - is there any other way that we can verify that our connection to Cloudflare is indeed over TLS?

**Comment by qdm12** [comment]
Hi there,

You can refer to [this section for that](https://github.com/qdm12/cloudflare-dns-server/blob/master/README.md#verify-dns-connection), which ensures you use the DNS providers you specified. 

Regarding encryption, on top of trusting Unbound source code, if you have a router with deep packet inspection (or a program like Wireshark) it will detect DNS over TLS encrypted traffic.

Enjoy!
