### ISSUE TITLE
does not work after reboot

### ISSUE THREAD

**Issue by woiza** [qdm12/cloudflare-dns-server#27]
`$ docker-compose up` everything works as expected
`$ sudo reboot`

It does not work anymore...

`$ docker-compose logs`
`ERROR	cannot write to file "/unbound/root.hints": open /unbound/root.hints: permission denied`

`docker-compose down` and `docker-compose up` again  and everything is back to normal. Any idea on how to make sure the container/service functions properly after a reboot?

**Comment by qdm12** [comment]
Interesting, thanks for reporting.

Does it do the same error when you do `docker-compose stop`? It's likely that the file already exists and somehow it cannot overwrite it, I'll check the permissions flags used when creating the file.
