### ISSUE TITLE
Restore the ability to have an include.conf for unbound.

### ISSUE THREAD

**Issue by JayNewstrom** [qdm12/cloudflare-dns-server#29]
Before the rewrite, it was possible to use include.conf to do custom unbound configs. I was using that, and hope that it can be restored.

It appears as though it would be pretty easily added to https://github.com/qdm12/cloudflare-dns-server/blob/master/internal/dns/conf.go

With just an extra line.

Would you be willing to add it, or accept a contribution adding it?

**Comment by qdm12** [comment]
I can add it, probably tonight or tomorrow. Or happy to accept a PR. Although it would need a bit more, either an empty file include.conf (as it was better) or an env variable specifying the path to a file to import, and, if empty, does not add the include line in the configuration. What do you think? Thanks for the suggestion anyway, sorry for removing that feature :confused:

**Comment by JayNewstrom** [comment]
No worries about removing it!

I think the easiest would be to have it as an empty file in the image, and have the user can mount a file (with any name on their host) to that specific path in the container. Simple, and flexible!

I'll let you add it if you don't mind. Or I can get to it this weekend.

**Comment by JayNewstrom** [comment]
That fixed it. Thanks for the quick update!
