### ISSUE TITLE
DNS not working in conjunction with OpenVPN docker

### ISSUE THREAD

**Issue by thayneq** [qdm12/cloudflare-dns-server#3]
I have this package up and running (thanks for your help), but it seems to break in a specific condition:

- I have this docker container running with 53:8053/udp, and it works fine for clients on my LAN (192.168.2.X)
- I have another docker container running an OpenVPN server, which is set to give out IP addresses in the 10.8.8.X range. I have set this up with a route to make sure that 10.8.8.X clients can talk to the 192.168.2.X network.
- When a client connects to the OpenVPN server, it gets issued an IP and connects just fine. When I have the OpenVPN server use the cloudflare-dns-server as its DNS, things start to break. However when I have the OpenVPN server use any other DNS, such as 9.9.9.9 or 1.1.1.1 directly, the clients can resolve DNS queries just fine.

Troubleshooting:
- I have watched the logs of the cloudflare-dns-server container, and I can confirm that indeed the DNS traffic is getting to the container, because I see activity in the logs, so it doesn't seem like a docker setup issue.
- I tried modifying the unbound.conf file and commented out the private IP lines to see if that would make a difference, and it didn't appear to. (I was sure to only stop and restart the container, rather than rebuild, because obivously the unbound.conf would be over-written).

So for now I am not sure what else to try. Any ideas?

**Comment by qdm12** [comment]
The private addresses in unbound.conf just prevents DNS rebinding (no resolve of private IP address)

Are you running your openvpn server in a container? 

1. First try setting your router to use the NAS running the container as its DNS and check if openvpn works with DNS *192.168.1.1*?
1. Try setting the DNS of the NAS to the LAN IP of the NAS, does openvpn works with DNS=LAN IP? (Synology network settings or `/etc/resolv.conf`)
1. Are you sure the DNS request gets resolved correctly? Try with `docker logs cloudflare-dns-server | grep APARTICULARWEBSITEYOUVISITEDONYOURVPN`

**Comment by thayneq** [comment]
yes, I am running openvpn in a container.

1. when I set my router to use the NAS's container (cloudflare-dns-server at 192.168.2.2), clients on the LAN (192.168.2.X) can indeed resolve DNS queries, but VPN clients can not. Also, my VPN settings push DNS server (192.168.2.2) settings to clients, so changing the router's DNS doesn't do anything I think, as a DCHP request for DNS isn't made by the client to the router. When I disabled the VPN from pushing DNS, it didn't work either.

2. The NAS's DNS is already set to 127.0.0.1, which should point to the cloudflare-dns-server docker container. This is my default configuration. Changing this to 9.9.9.9 or something else doesn't seem to have any effect on the VPN's inability to route traffic properly.

3. It seems DNS requests *are* resolving correctly, or at least I think they are. Here is an example. I have a remote VPN client connected to the docker OpenVPN server. It gets IP 10.8.8.6, and gets a DNS of 192.168.2.2. When I try to navigate to http://www.grc.com, here is what I see in the logs of the cloudflare-dns-server (you tell me whether this looks correct, as I'm not sure what a good DNS request should look like).




```
docker logs dns 2>&1 | grep -i grc.com
[1542412154] unbound[36:1] info: validator operate: query grc.com. A IN
[1542412154] unbound[36:1] info: resolving grc.com. A IN
[1542412154] unbound[36:1] info: processQueryTargets: grc.com. A IN
[1542412154] unbound[36:1] info: sending query: grc.com. A IN
[1542412154] unbound[36:1] info: 0RDd mod1 rep grc.com. A IN
[1542412154] unbound[36:1] info: iterator operate: query grc.com. A IN
[1542412154] unbound[36:1] info: response for grc.com. A IN
grc.com.        IN      A
grc.com.        9085    IN      A       4.79.142.200
[1542412154] unbound[36:1] info: finishing processing for grc.com. A IN
[1542412154] unbound[36:1] info: validator operate: query grc.com. A IN
[1542412154] unbound[36:1] info: no signer, using grc.com. TYPE0 CLASS0
[1542412154] unbound[36:1] info: validator: FindKey grc.com. A IN
[1542412154] unbound[36:1] info: target keyname grc.com. DNSKEY IN
[1542412154] unbound[36:1] info: next keyname grc.com. DNSKEY IN
[1542412154] unbound[36:1] info: generate request grc.com. DS IN
[1542412154] unbound[36:1] info: validator operate: query grc.com. DS IN
[1542412154] unbound[36:1] info: resolving grc.com. DS IN
[1542412154] unbound[36:1] info: processQueryTargets: grc.com. DS IN
[1542412154] unbound[36:1] info: sending query: grc.com. DS IN
[1542412154] unbound[36:1] info: 0vRDCD mod1  grc.com. DS IN
[1542412154] unbound[36:1] info: 1RDdc mod0 rep grc.com. A IN
[1542412154] unbound[36:1] info: iterator operate: query grc.com. DS IN
[1542412154] unbound[36:1] info: response for grc.com. DS IN
grc.com.        IN      DS
[1542412154] unbound[36:1] info: finishing processing for grc.com. DS IN
[1542412154] unbound[36:1] info: validator operate: query grc.com. DS IN
[1542412154] unbound[36:1] info: validator: inform_super, sub is grc.com. DS IN
[1542412154] unbound[36:1] info: super is grc.com. A IN
[1542412154] unbound[36:1] info: validator operate: query grc.com. A IN
```





<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thayneq** [comment]
note that my service is named "dns" as it's easier to type than "cloudflare-dns-server"

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thayneq** [comment]
whoa this is strange. I tried something different and I got it working (and I don't know why). Instead of pointing my OpenVPN clients directly to the DNS server container (192.168.2.2), I pointed them at the router, which in turn is set to give DNS of 192.168.2.2. And this worked! But why? Why would it be any different?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thayneq** [comment]
no, something is wrong. My VPN tells me it is pushing 192.168.2.1 (router). My router is set to only git 192.168.2.2 (synology running dns). But when I connect a client, and go to dnsleaktest.com I'm seeing my DNS servers as OpenDNS, and I'm seeing zero traffic on my actual dns container. what the f....

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qdm12** [comment]
Ok the DNS appears to work, a weird problem yet again!

Can you try running the DNS as root with `--user="root"` or `user: root` for compose, with `LISTENINGPORT=53` and by having the VPN container use the DNS with its bridge IP address (172.168.10.5 for example, check with `docker network inspect bridge`).

**Comment by thayneq** [comment]
Ok now that seems to work! Monitoring both VPN and dns dockers, I can see that the VPN server is issuing the correct DNS setting to the client, and the client's DNS requests and getting resolved and routed properly! Is this a final workable solution, or are there more steps you would like me to try? I suppose this solution will be fine as long as I can hard-code the 172.168.X.X address on the dns container.

**Comment by thayneq** [comment]
this seems to be an elegant solution actually: I have created a custom network, and added both containers to it using docker-compose, along with a hard-coded IP4 address. The only down-side I can see is that this now requires binding on port 53 inside the container, and thus hitting my other mysterious issue. For now I'll just run as root and hope for the best!

**Comment by qdm12** [comment]
An ideal solution would be to run the DNS on port 8053 and have an iptables re route to forward port with destination 53 from the VPN to port 8053. It's probably one line to add to the host iptables (synology has iptables, try `iptables -L`) in the the DOCKER_USER chain I think.

An easier alternative I'll try today is using `su-exec` to drop root privileges when you run the container as root. Because for now Unbound runs as nonrootuser but the system is still running as root.

If this doesn't work a final security alternative is to have user UID mapping with Docker (in example root in the container maps to uid 5000 on the host, so not root). Not perfect but better than root on the container AND host.
