### ISSUE TITLE
https://1.1.1.1/help reports that I'm not using HTTPS/TLS

### ISSUE THREAD

**Issue by flyize** [qdm12/cloudflare-dns-server#4]
So I just set this up.  

* Blocked port 53 except for Docker server (verified by trying to use external DNS servers from my client)
* Started container, pointed my client machine's DNS *only* at the IP of the Docker server
* Browsed to https://1.1.1.1/help

**Debug Information**
Connected to 1.1.1.1 | No
Using DNS over HTTPS (DoH) | No
Using DNS over TLS (DoT) | No
AS Name | Cloudflare
AS Number | 13335
Cloudflare Data Center | DFW

**Connectivity to Resolver IP Addresses**
1.1.1.1 | Yes
1.0.0.1 | Yes
2606:4700:4700::1111 | No
2606:4700:4700::1001 | No

What am I missing?

**Comment by qdm12** [comment]
It looks like (from my Windows client machine)[https://1.1.1.1/help](https://1.1.1.1/help) does not really work. I have set my DNS to 1.1.1.1 and 1.0.0.1 on my computer and it shows the same information as yours. **Does it work for you if you manually set the DNS of your machine to 1.1.1.1 / 1.0.0.1** ?

In addition, I have tried to run this container on both my server and local Windows machine. Using the environment variables `-e VERBOSITY=5 -e VERBOSITY_DETAILS=4` with `docker logs -f dns`, some traffic with `1.1.1.1` over TLS without any warning or error can be seen.

**Comment by flyize** [comment]
If I install and activate SimpleDNSCrypt on my Windows machine, https://1.1.1.1/help reports perfectly that I'm using DoT.  As soon as I switch back to this Docker container, it fails.  So it seems that the test site does work correctly...

**Comment by qdm12** [comment]
> If I install and activate SimpleDNSCrypt on my Windows machine, https://1.1.1.1/help reports perfectly that I'm using DoT. As soon as I switch back to this Docker container, it fails.

*SimpleDNSCrypt* is a client to Cloudflare DNS servers. *Unbound* is both a client to Cloudflare DNS servers and a (caching) DNS server. This is why it is not detected directly on [https://1.1.1.1/help](https://1.1.1.1/help). If you still don't trust it, refer to the logs with high verbosity as I mentioned before and to the [source code of Unbound](https://github.com/NLnetLabs/unbound).

> And what would manually setting DNS to 1.1.1.1 prove?

That it should show `Connected to 1.1.1.1 | Yes` but does not (oddly).

> Isn't the goal here to use HTTPS/TLS

TLS not HTTPS (HTTP with TLS)

**Comment by flyize** [comment]
Okay, that makes sense.

Is there any online test I can run to verify that everything is working properly then?

**Comment by qdm12** [comment]
Check the edit part of [my comment above](https://github.com/qdm12/cloudflare-dns-server/issues/4#issuecomment-453215694) you can try with [https://www.dnsleaktest.com](https://www.dnsleaktest.com)

You can also check DNS SEC at [https://en.internet.nl/connection](https://en.internet.nl/connection)
