### ISSUE TITLE
Container Fails to start

### ISSUE THREAD

**Issue by stumpylog** [qdm12/cloudflare-dns-server#45]
2020-12-15T13:23:43.321Z	ERROR	unbound version: exit status 127,
Running version latest built on 2020-12-15T03:39:51Z (commit a074849)

With the latest version, it looks like some problem with unbound. Maybe an unexpected version string?

**Comment by qdm12** [comment]
Thanks for letting me know! The latest Unbound from the edge repo on Alpine seems broken (didn't test my bad too!), I reverted to the latest stable version and it works now. Cheers!

**Comment by stumpylog** [comment]
Thanks for the quick fix, working good now for me as well.
