### ISSUE TITLE
surveillance list

### ISSUE THREAD

**Issue by aikidoka** [qdm12/cloudflare-dns-server#46]
Is this just a list of government sites?

I was only alerted to this as my wife is a lawyer and needs to access these types of sites regularly. (not a big deal to disable)

I am just curious what the thought process was behind the list?

**Comment by qdm12** [comment]
Hello! Good question!

The block lists are built everyday by a program I have running which gathers them from various sources. For the surveillance hostnames, it's built from 2 sources: [source code](https://github.com/qdm12/updated/blob/master/pkg/hostnames/builders.go#L9-L15). The second one includes 'excessive Gov URLS' so I can change that.

And to be honest, this is focused on US surveillance but I should probably include surveillance from **MANY** other countries as well.

On a side note, you can also use the environment variable `UNBLOCK` to unblock specific hostnames.

Anyway, let's keep the issue opened and I'll investigate more sources to use for that one and not bundle *all* US gov websites either.

**Comment by qdm12** [comment]
The surveillance block list now does not include the excessive list of gov hostnames, I'll close the issue for now. Thanks!
