### ISSUE TITLE
Multi-Arch Docker Hub image?

### ISSUE THREAD

**Issue by JasonSwindle** [qdm12/cloudflare-dns-server#9]
Howdy,

I would love an ARM based image in Docker Hub as a tag. :)

**Comment by qdm12** [comment]
Hi there,

Yes I am working on it, I am configuring a Raspberry Pi with some CI pipeline/Github webhook to build ARM images for all architectures and push them to Docker Hub. It might take a few days still. I'll close the issue when done! Thanks

**Comment by qdm12** [comment]
I'm making progress, although I'm reworking the whole tagging/releasing thing across my Docker images. Ideally you could pull the image from a common tag for the right CPU architecture using a Docker manifest on Docker Hub, and you would have release tags so you can fallback to a previous version. I'll keep you updated!

**Comment by barbz127** [comment]
Hi,
I'm wondering if you have had any luck with the multi arch builds? I'm currently running this image on a x86 host but looking to migrate to a pi.
Thankyou

**Comment by qdm12** [comment]
Hi there, unfortunately my raspberry Pi seems to have died so I don't really have an ARM device to build ARM docker images :disappointed:

So your best bet is to build it with the readme instructions, it's just a one liner so it shouldn't be that bad :)

I will ping back here once I replace my raspberry pi and setup a pipeline for ARM.

**Comment by qdm12** [comment]
Hi all, I am working right now on it, moving away from Docker hub automated builds to another CI (Travis or Circle CI), I'm exploring multi-arch possibilities. I will let you know once it's done! Probably in 2-3 days.

**Comment by qdm12** [comment]
Hi @barbz127 I just made it on [another Docker image](https://github.com/qdm12/private-internet-access-docker) where it builds for all architectures and pulling the latest tag will simply get you the right image for your machine, so it's gonna be great! I will add it tomorrow and ping back here. Thanks for your patience.

**Comment by barbz127** [comment]
Thankyou!
